import type { Metadata } from "next";
import { Inter, Playfair_Display } from "next/font/google";
import "./globals.css";
import Header from "@/_layout/Header";
import Footer from "@/_layout/Footer";

const inter = Inter({ subsets: ["latin"], variable: "--inter" });
const playfairDisplay = Playfair_Display({
  subsets: ["latin"],
  variable: "--playfairDisplay",
});

export const metadata: Metadata = {
  title: "A I P",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${playfairDisplay.variable} tw-bg-bgLightPeach tw-font-inter no-scrollbar tw-overflow-x-hidden`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
