import type { Metadata } from "next";
import { Inter, Playfair_Display } from "next/font/google";
import "./globals.css";
import Header from "@/_layout/Header/Header";
import Footer from "@/_layout/Footer";
import localFont from "next/font/local";

const inter = Inter({ subsets: ["latin"], variable: "--inter" });
// const playfairDisplay = Playfair_Display({
//   subsets: ["latin"],
//   variable: "--playfairDisplay",
// });
const playfairDisplay = localFont({
  src: "../fonts/Playfair_Display/static/PlayfairDisplay-Regular.ttf",
  variable: "--playfairDisplay",
});
const playfairDisplayItalic = localFont({
  src: "../fonts/Playfair_Display/static/PlayfairDisplay-italic.ttf",
  variable: "--playfairDisplayItalic",
});

export const metadata: Metadata = {
  title: "A I P",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${playfairDisplay.variable} ${playfairDisplayItalic.variable} !tw-overflow-y-auto tw-bg-bgLightPeach tw-font-inter no-scrollbar tw-overflow-x-hidden`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
